version: "3.8"

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres-planpp
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_DB: pgdb
        POSTGRES_USER: pguser
        POSTGRES_PASSWORD: pguser
    volumes:
      - ./database/.dbdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-planpp
    command: npm start
    volumes:
      - ./backend/:/app/backend/
    ports:
      - 3001:3001
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command : npm start
    container_name: frontend-planpp
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app/frontend/
    restart: always
    stdin_open: true
